const model_of_ukma = {
    "faculties":[
        {
            "id":"guid"
            "faculty":"string",
            "specialities":[
                "name":"string"
            ],
            "teachers":[
                {
                    "id":"guid",
                    "fullName":"string",
                    "email":"string",
                }
            ],
            "subjects":[
                "id":"guid"
                "name":"string",
                "year":"datetime",
                "year_part":integer,
                "maxNumberOfStudents":integer,
                "minNumberOfStudents":integer,
                "teachers":[
                    "lectures":"teacher_id",
                    "practices":"teacher_id"
                ]
            ],
            "students":[
                "id":"guid",
                "fullName":"string",
                "email":"string",
                "enter_year":"datetime",
                "graduation_year":"datetime",
                "student_subjects":[
                    "subjectId":"guid",
                    "grade":integer
                ]
            ]
        }
    ]
}